<?php

    // Testing data to generate panels
    // This testing data was generated by ChatGPT (Jan 9 version) on 1/19/23
    $projects = array(
        "a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6" => array(
        "id" => "a1b2c3d4-e5f6-a7b8-c9d0-e1f2a3b4c5d6",
        "project_name" => "My Project",
        "project_creator" => "John Doe",
        "screenshot" => "https://via.placeholder.com/230x180"
    ),
        "f1e2d3c4-b5a6-f7e8-g9h0-i1j2k3l4m5n6" => array(
        "id" => "f1e2d3c4-b5a6-f7e8-g9h0-i1j2k3l4m5n6",
        "project_name" => "Another Project",
        "project_creator" => "Jane Smith",
        "screenshot" => "https://via.placeholder.com/230x180"
      ),
        "o1p2q3r4-s5t6-u7v8-w9x0-y1z2a3b4c5d6" => array(
        "id" => "o1p2q3r4-s5t6-u7v8-w9x0-y1z2a3b4c5d6",
        "project_name" => "Third Project",
        "project_creator" => "Bob Johnson",
        "screenshot" => "https://via.placeholder.com/230x180"
      ),
        "e1f2g3h4-i5j6-k7l8-m9n0-o1p2q3r4s5t6" => array(
        "id" => "e1f2g3h4-i5j6-k7l8-m9n0-o1p2q3r4s5t6",
        "project_name" => "Forth Project",
        "project_creator" => "Emily Davis",
        "screenshot" => "https://via.placeholder.com/230x180"
    ),
        "u1v2w3x4-y5z6-a7b8-c9d0-e1f2g3h4i5j6" => array(
        "id" => "u1v2w3x4-y5z6-a7b8-c9d0-e1f2g3h4i5j6",
        "project_name" => "Fifth Project",
        "project_creator" => "Michael Brown",
        "screenshot" => "https://via.placeholder.com/230x180"
    )
);

?>